---
# file: datomic/tasks/main.yml
# This script is for launching the datomic docker container


## Setting up host machine
##
#- name: create datastore folder
#  file: path=/datastore state=directory mode=0775
#
#- name: create Datomic datastore directory
#  file: path=/datastore/datomic state=directory mode=0775
#
#- name: create Datamic data directory
#  file: path=/datastore/datomic/data state=directory mode=0775
#
#- name: create Datomic config folder
#  file: path=/datastore/datomic/configs state=directory mode=0775
#
#- name: copy config files
#  copy: src=./configs/free-transactor.properties dest=/datastore/datomic/configs/
#
#- name: creating postgresql image
#  docker_image: >
#    name=wormbase-postgresql9-4
#    tag=latest
#    path="./roles/postgresql/files"
#    state=build

- name: running postgresql container
  docker:
    name: wormbase-database
    image: postgres:9.4
    detach: true 
    env: { POSTGRES_PASSWORD: "password"}
    state: started
    ports: 
      - "5432:5432"
    expose: 
      - 5432
    volumes:
      - '/var/log/postgresql/data:/var/log/postgresql/data:rw'
