- name: adding Docker yum repository
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
  when: ansible_os_family =="RedHat"

- name: install Docker
  yum: name=docker state=latest
  when: ansible_os_family =="RedHat"

- name: start Docker
  service: name=docker state=started

- name: Add user to docker group
  user: name=ec2-user group=docker

- name: install pip
  yum: name=python-pip state=latest
  when: ansible_os_family =="RedHat"

- name: install docker-py
  pip: name=docker-py state=present version=1.2.3
  
- name: create datastore directory
  file: path=/datastore state=directory mode=0775

- name: install xfsprogs
  yum: name=xfsprogs state=latest

- name: install xfsdump
  yum: name=xfsdump state=latest
