os:
  - linux

language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
   - sudo yum update
   - sudo yum -y install python-pip

install:
   # Install Ansible.

   - pip install ansible

   # Add ansible.cfg to pick up roles path.
   - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
   - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
   - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
       | grep -q 'changed=0.*failed=0'
       && (echo 'Idempotence test: pass' && exit 0)
       || (echo 'Idempotence test: fail' && exit 1)


