sudo: required

os:
    -linux

language: python
python: "2.7"

install:
   - pip install ansible

script:
   - echo localhost > inventory
   - ansible-playbook --syntax-check tests/role.yml
#   - ansible-playbook -i inventory --syntax-check role.yml
#   - ansible-playbook -i inventory --connection=local --sudo -vvvv role.yml
